### PR TITLE
missing package kmod-nf-nathelper-extra

### PR DESCRIPTION
**Pull request by nstrelow**
kmod-ipt-nathelper was deprecated and removed in previous commit. This broke VPN access.
The new package is called kmod-nf-nathelper and replaces kmod-ipt-nathelper.
kmod-nf-nathelper-extra installs both kmod-nf-natheler and kmod-nf-nathelper-extra. Both are needed for working VPN (tested on v9 with uni-potsdam VPN).

### CODE REVIEW

**Comment by fniephaus** [comment]
Thanks, @djnilse.
Could you also please update the [.travis.yml](https://github.com/fniephaus/WohnheimRouter/blob/master/.travis.yml) accordingly?

**Comment by djnilse** [comment]
@fniephaus I added it.

**Comment by fniephaus** [comment]
Thanks! Travis should update the following file automatically in a couple of minutes:
https://github.com/fniephaus/WohnheimRouter/blob/master/firmwares/openwrt-ar71xx-generic-tl-wr841n-v9-squashfs-factory-latest.bin

**Comment by djnilse** [comment]
Nice! Need to look into travis stuff ;D

**Pull request merged**
